/* data.js */

const driveImageMap = {
  "list.txt": "1AODzCzDOLrhjG_TB1yUwpFn6vAvnbaAq",
  "RosannaL1_illust.png": "13yupD6QwQRWXmlJ32srFeuEMxXx7t_vb",
  "RosannaL2_illust.png": "1MPsUK0akfsf9uSpzYAsdJYV0P3WZbESo",
  "WeaponIcon_RosannaWeaponDesperadoD.png": "16SmWRBD0z15b5zun6FoHc602DXZHRwpK",
  "WeaponIcon_RosannaWeaponDesperadoF.png": "173trMGxmqGwwyeNVk5ndLBtXgqWjwgc7",
  "WeaponIcon_RosannaWeaponBasicL.png": "17AyIlyBV0UINcfb-encS6jmdmgehTZuP",
  "WeaponIcon_RosannaWeaponElegantL.png": "19irPLWKgXprAyq_C952NJW-ZKi0sDZ8q",
  "WeaponIcon_RosannaWeaponElegantD.png": "19xjeEyvz6KlVKdpsVGO1_y5UPF3uvxBU",
  "WeaponIcon_RosannaWeaponDesperadoE.png": "1D_ue3Sx1A-CBKeRc-PM1a4ezrH6ewnPF",
  "WeaponIcon_RosannaWeaponElegantW.png": "1FXpWez3XDb4ILWm8tpaEpvU22RZms4nM",
  "WeaponIcon_RosannaWeaponBasicE.png": "1K5hTE-BvPkwzOhE7VJJuUYZ1rFe8IQ0A",
  "WeaponIcon_RosannaWeaponDesperadoW.png": "1OSxHrAnbfg3WnMqV2uNQqNlwAsdSC_dp",
  "WeaponIcon_RosannaWeaponElegantF.png": "1RJJ2ZVZn2XpGH9O8LPIBydzk_rLWrpAo",
  "WeaponIcon_RosannaWeaponBasicF.png": "1StSQuhXOu9YAz3cyVPBpMHQMUGu15gur",
  "WeaponIcon_RosannaWeaponElegantE.png": "1cFJbmkROoiLNWfMUC6-ZyUeXymRvaqTG",
  "WeaponIcon_RosannaWeaponBasicW.png": "1i34BNBO4_Roan3TxFcwLmtGaltRmZvNy",
  "WeaponIcon_RosannaWeaponDesperadoL.png": "1n3aWRQpy9bE6yAztRcw_OhkR8N7tQ9e1",
  "WeaponIcon_RosannaWeaponBasicD.png": "1pieHKTnmcnq1Rkx7KJUu_UUvTVCu4_Mt",
  "icon_rosanna.dark.skill3.png": "10U8ZMGcFslcpHlqekV8YZbdr0I0mdu5o",
  "icon_rosanna.water.skill1.png": "17hUm_MTvk51NmcH_BF3yMGovwR-ZUr-S",
  "icon_rosanna.water.skill3.png": "1ACfwqWIAXLcojSvxM6A_bMF366b1B8Kx",
  "icon_rosanna.fire.skill1.png": "1D-_Vev79ss3dw2RsoQpu-WsS5sy0WlOS",
  "icon_commander_skill_rosanna.water.png": "1IUnJPgbl8vvaznq_IlGQUDfz5THE4Cjg",
  "icon_rosanna.light.skill3.png": "1JLD0GC64SjIWJNlVqEEDWW7a83hohFas",
  "icon_rosanna.fire.skill2.png": "1NVplGQZcPI2jnRcOklgJ7VUQafC84zFu",
  "icon_rosanna.fire.skill3.png": "1OhvoxNNQENlztmsYNpP_1ktyPfdi8aba",
  "icon_rosanna.light.skill1.png": "1SffKRnFcLohzGfFEOc5ixH6o5ySK1qhL",
  "icon_rosanna.earth.skill3.png": "1V2JUYh69d6UNxRW4mH65dTNwRQLT_3Ij",
  "icon_rosanna.earth.skill1.png": "1d1Hk-_OXG6kiPzd7vXUufGOvvYe34Ole",
  "icon_rosanna.water.skill2.png": "1lTOtYEaKhLCOYWQYRiJJ4-AFrpDIexU4",
  "icon_rosanna.light.skill2.png": "1t2OpjIRG12VyEOnX5c59OL6ypQMxebaO",
  "icon_rosanna.earth.skill2.png": "1vBD1dsd0subt4JTCEm0WKZSHqEyYZLH9",
  "icon_rosanna.dark.skill2.png": "1yZgqLYFXvIgf5hDTJFUaky0i41Mjjyc6",
  "icon_rosanna.dark.skill1.png": "1zbi4uoaIfhLpNomP3bOl7qJ1eEv9_Ier",
  "icon_box_5thanniversary_rosanna_light.png": "1Ey9uosjcHI6FGxzBA96t6UlLDss4UN_B",
  "RosannaW1_illust.png": "1T0smgX_0cPnGmd8bzGRjZAr77evhEEAh",
  "RosannaW3_illust.png": "1UXTbYXxmZ_xAgXpvbr1HsvLVa0MGwCY6",
  "RosannaD2_illust.png": "11Y8QK_YpKp9Zd5bf3lKI9kvCpy02WCeq",
  "RosannaL3_illust.png": "12iX1LzV9juZC4cQrKZG-IsvBoPAL6sTq",
  "RosannaW2_illust.png": "1puneM0TBc3eSJq7Lc_uUGaVC7sxnXwZG",
  "RosannaD1_illust.png": "1qtpQfZxjRMHoZYy9BQyMU6sPyMw7Rak1",
  "RosannaSummerwear2021W_illust.png": "1V4Z49kSmNUM0ZaoCA2Hc__RecdHjkRGU",
  "RosannaSummerwear2021RareW_illust.png": "1gCaYV4OVd5RlR731hcNmR4e3WfNSXzB_",
  "RosannaF3_illust.png": "1iPln29xgJBQZSxP8YWQGFD5MeW8WrI9Z",
  "RosannaD3_illust.png": "1l-uRfhYmzXAiw1ZdMstZ-4e7IxwWhl8F",
  "RosannaF1_illust.png": "1GsmXGS9L14uUljxuwbJVtAfsnsWjul-z",
  "RosannaF2_illust.png": "1Hg00jc4vkCdKSP2eVDsk5uhYRK921ZwN",
  "icon_HelgaBeautyMinishipA1.png": "1YZ0H5B3QXVfeS-_jnnLgTwbUzJHoMVfO",
  "icon_RicardoBeautyDollB1.png": "13hOjtNajn6G7rnGbdZzM7dx-hV2XHXJk",
  "icon_BiancaBeautyDollA1.png": "12me2OHOyRdmbEKBES_AqQQQBfpQ1Ig56",
  "icon_RosannaBeautyGlassesE2.png": "1I99l7xYfTQQdmpxQ3p3sYLkOfUYPMRNo",
  "icon_RosannaBeautyBdayB3.png": "1OjiLIiQnFLhcNlM4FwdliibuRObRp7AL",
  "icon_RosannaBeautyStarearingA4.png": "1ZFGWczHrez1cY27ap-q8lhzinR57cSA0",
  "icon_RosannaBeautyGlassesC1.png": "1cEX5GE0M9rA1jLcU5M_B3bd1QGashP9y",
  "icon_RosannaBeautyBdayA5.png": "1eET0oXVtcbqSvJv4dkQqA6-qWNfuVN0i",
  "icon_RosannaBeautyPearlpinA2.png": "1jQC-SAJeq8z7OwyHaQmunTX_S4T7Wlsc",
  "icon_RosannaBeautyChinchillaearsA1.png": "1-wJrrN22j_nm-W96ILKteVGYHZCn9LFl",
  "icon_RosannaBeautyChinchillaearsA2.png": "11kAXu2ZmurCVK-TFCgp8Im44ficI5zhb",
  "icon_RosannaBeautyBdayA3.png": "15vtoH_79UzMjWidRfmMeZ0OwyfrpMjN3",
  "icon_RosannaBeautyBdayB2.png": "16PqhYsDFP8s3NgtQNO-b8__Urbhg9NZb",
  "icon_RosannaBeautyStarearingA5.png": "19WXnxlCr9Q1bwvYBGaloPvZLnoa2CZmA",
  "icon_RosannaBeautyPearlpinA1.png": "1C-lbb_UP7SGOwnsYs_gASTWCyV-_5PtW",
  "icon_RosannaBeautyStarearingA2.png": "1DC6VDaefih_R1lxHbFgpoCiJUzVkepFW",
  "icon_RicardoBeautyYoungrosannadollA1.png": "1HgYKTWAbA5lltdebtRHDXfniykQ1VPyS",
  "icon_RosannaBeautyBdayB1.png": "1Hla95NnO_fSm6anucYcmWgWXMuJdYKik",
  "icon_RosannaBeautydollEA1.png": "1Nel-aM2KW9DV2EJhBArF1enxVsc9eoFI",
  "icon_RosannaBeautyStarearingA3.png": "1RF-OWhEe9CQu_ivFapZaeW034nMGBCc1",
  "icon_RosannaBeautyBdayA2.png": "1S_OS-Ztr6uJyKK8pstqZ9QJw7QiReax7",
  "icon_RosannaBeautyChinchillaearsA5.png": "1ZBaH4VyuTMidHu7C6e2j1j3DQ_W45tgY",
  "icon_RosannaBeautyChinchillaearsA4.png": "1ZafjTzhwu3YrAZUkzFag5KT9ar4HUL4V",
  "icon_RosannaBeautyGlassesA1.png": "1aRG3xaWGvLNqOGiN2hI5M031osR_XAhY",
  "icon_RosannaBeautyMinishipA1.png": "1aakwLQourx6IMXwA3JUd8URLQ45UKrtp",
  "icon_RosannaBeautyGlassesB1.png": "1azmrEna8ODnn87hOEQS_5XDYlIwVJHSp",
  "icon_RosannaBeautyChinchillaearsA3.png": "1b1a_qrJHu0mHoLm_VB0hg1N2czf2OfWq",
  "icon_RosannaBeautyPearlpinA3.png": "1clceYOqiRR_cAVjbg6RTlF19XQBKal7W",
  "icon_RosannaBeautyBdayB5.png": "1dP6UMnxh_EWFqfIEIgDii4W8peYq-CrF",
  "icon_RosannaBeautyMinishipB1.png": "1eE0LDCdCCdqu2rkP3CcUgW1IOLu7P6je",
  "icon_RosannaBeautyMinishipC1.png": "1epaYXKprv-kJ6p42SwvjpaPAaqCXluRC",
  "icon_RosannaBeautyStarearingA1.png": "1hapTcdkaxlYMkWF9i18HeVTrb8D-RwFP",
  "icon_RosannaBeautyBdayA4.png": "1rEbhpCd-Qu4PXT-qND7MswyDPMfxcS5I",
  "icon_RosannaBeautyBdayA1.png": "1rKBAOgmm0BuSAb4z9a4y_wTWLoh9YSlA",
  "icon_RosannaBeautyGlassesD1.png": "1ssVYTnlNDUPYaQWFLF_S-rh_G2uG6xEG",
  "icon_RosannaBeautyBdayB4.png": "1vi3thxx2VS3P5_ROvnbP8F013CMisQMA",
  "icon_RosannaBeautyPigeonA1.png": "1y96m9iRztm9ix4gVPQzHgq2cLmxDIJtN",
  "icon_RosannaBeautyGlassesE1.png": "1z6k9TcXdKzdY1S-tZwHuDCzx_usYOOJi",
  "RosannaF1_icon.png": "10RlAU9aLAIb_srtZ4F0-wqj1iMFErLj9",
  "RosannaD3_icon.png": "11DLWU-M8abRUgietf_8OL9bxLjgF1GkO",
  "RosannaW3_icon.png": "13tFGGvG_kWpFh31ijs2qRuF08sY4ZBib",
  "RosannaF2_icon.png": "1DzuZ-gdi-cYQg_g7w_bOT_UAUVVk0sId",
  "RosannaW2_icon.png": "1J1XMmOj9dQFqhH-OgbKxvuo6YuItxSaQ",
  "RosannaL3_icon.png": "1RDJboEIPGBKNkHj0PjjG3SuIlyJ50uUT",
  "YoungRosannaW2_icon.png": "1TECb-XofsTTtg9UYFqgtbNK5bYTPDUmQ",
  "RosannaE1_icon.png": "1Ul4nYX5bg3vzpm4WP9NfzbK9U9_bszpu",
  "RosannaSummerwear2022W_icon.png": "1azlSHT8C0BlxJ1KvxhQvbu8OT4Kq_bhZ",
  "RosannaSummerwear2021RareW_icon.png": "1btq33kB4WQkDziNbsKVdtk6nS73sOi98",
  "RosannaD2_icon.png": "1e2rGjVHkUNGx19KvEsWyNSudz_54KnT5",
  "RosannaHolidaywear2022RareW_icon.png": "1hOl2TjOEBGFXh5Hm24z2xKy27nqViwWi",
  "RosannaL2_icon.png": "1nRPJAs9puHbfp6k14umqt_wGzUHrwwqm",
  "RosannaSummerwear2021W_icon.png": "1tYQLS0CLdXIn5zjq-8IsCtBx0z3cH9Bs",
  "RosannaW1_icon.png": "1tne5czH-waElzC-Bj53EO7L02uqotqtm",
  "RosannaD1_icon.png": "16a-PkZpmCP-8W5FLDsGuj_fedg3XsRhE",
  "RosannaE2_icon.png": "17ffaNn8XC1-gdPDw-s6-jbuZW293-1WT",
  "RosannaL1_icon.png": "1BQjz2iIUNKTQVyxL9x_GB_Jo39egABvt",
  "RosannaHolidaywear2022W_icon.png": "1UtJf6iYpv9qkyFaKLFoFL23OLZ1jgJ-g",
  "RosannaF3_icon.png": "1dK0jp8Y0_NAl5S56DuBf9ZN0y73KiW8N",
  "RosannaE3_icon.png": "1oXYYcH5L8q9eFR5C1X3T1Yxf3W2lpvNi",
  "RosannaSummerwear2022RareW_icon.png": "1qjWyStuuKm2w6V3uKFRnDf-wsSvV6LMZ",
  "RosannaL1_portrait_tilt.png": "13-7U1MyC8MzVrF2JRghsEjrwH4VUKAZ5",
  "RosannaF3_portrait_tilt.png": "13-_QFe-XQupU1Y7csqPU67LxIPcBUpiB",
  "RosannaE2_portrait_tilt.png": "1479VjT-gG57CK2TRqJCufVfxKgUZDP7P",
  "RosannaL3_portrait_tilt.png": "1C0mhb1MqNFFoVXZ_awCVxU3cCcUrRxqL",
  "RosannaW1_portrait_tilt.png": "1Eah8Pd1XHTjMerWiduZPtzM2Bk0NB6op",
  "RosannaL2_portrait_tilt.png": "1I9dqO3-nnuo3QNp9rBScG-I95q6ibuN7",
  "RosannaF2_portrait_tilt.png": "1NLyJ7EgyI8fPEf07stCCzh6hbbsVd56o",
  "RosannaD3_portrait_tilt.png": "1docmYbfrcpC5pg319RbvYpAW95Fv3aUU",
  "RosannaW3_portrait_tilt.png": "1e2oALRzdAje16K2IoKbeCqRDmLSeruhj",
  "RosannaE3_portrait_tilt.png": "1vQy72Z6GmPordLwSrrHuW1ds9Z0p8NF7",
  "RosannaD1_portrait_tilt.png": "1wtIZWg1DwylZlkf-DHYwGLliLMJEd5LE",
  "RosannaF1_portrait_tilt.png": "1zTMGog8sQUHnmUIcqlE_HVm5UQaN4Lja",
  "RosannaW2_portrait_tilt.png": "1ROJf-bwAmPWykUBZD6a6tf8DStjeN6jM",
  "RosannaD2_portrait_tilt.png": "1T2NZvpQiRADCeodBF-ElmZpOcphzzV9X",
  "RosannaE1_portrait_tilt.png": "1VhJfP8Iu3TgOYqqVPocLn5Bj-gAW3O6v",
  "photocard_bday_rosanna_water_illust.png": "1FfnHBjOwU9aKa8xyB7eQs56dWOzAidCM",
  "shop_newyear2025_illust.png": "1m7N34EEW90BS5PBR_quz3St4xgH3oo9V",
  "bday_sd_dark_rosanna_illust.png": "1HqQ0nn-0RaNSudisCbpe_UEre6pGb81O",
  "bday_sd_fire_rosanna_illust.png": "10EtjYYfhfMpfB7X67Pu_CLJaj1AUZccc",
  "photocard_bday_rosanna_light_illust.png": "1Gwbtqcoziv4Y62dKZDIex7iNHD1xTNiN",
  "shop_chuseok2025_illust.png": "1S7iqntB8LJ6fe6g19CQSmHXOiJuQVF6Y",
  "shop_earlysummer2024_illust.png": "1tq41XQCuf36d_AzP5U8Qv--1eAWl2Zwq",
  "shop_summer2021_illust.png": "1cwZjcCoKuzDTdKOy7fShjH-egWDmHmgD",
  "photocard_bday_rosanna_dark_illust.png": "1s9GGE8c4yFbEKzFvfhlxO0j1MQ-UoCZp",
  "shop_holiday2021_illust.png": "1S_DuUzt_AM0Q7Rzq8bpCNXtfeX_LBuXB",
  "photocard_sidestory_mu_rosanna_illust.png": "1Z26BbUfIR0o6QavFl1pey4S1S2a3fzLT",
  "RosannaE2_illust.png": "14895rXz5uHw-PbhekzsIH7XWZBmAQREd",
  "RosannaE1_illust.png": "1LWGNFYn51X6KExnqrcacGhi2ONVY1yHu",
  "RosannaE3_illust.png": "1VQFBjjWqgVUQdt7BJSh94QX-qqtES6wx"
};


const driveVoiceMap = {
  "voices.txt": "1ih03LQ4afkqvv5zJkovbdMrC6W4GYays",
  "Rosanna_W_voice_kr_wound-12.wav": "1JFNfgFRbccdcyDSsmXCno3MZSrBkJjzJ",
  "Rosanna_W_voice_kr_wound-06.wav": "12NaefiHAF3F-QqGX1U6dQs6RynMPlVnf",
  "Rosanna_W_voice_kr_welcome2-02.wav": "1D1Ukx4mCIcGchOTeaa_9VlbVVSU67Ewg",
  "Rosanna_W_voice_kr_welcome1.wav": "1KRwWj9A6O_kzUT5vKCoT2JqWD0HtPHT4",
  "Rosanna_W_voice_kr_wound.wav": "1lERgnSIQ0FNeifPdtG5hURbnzsAC-xmq",
  "Rosanna_W_voice_kr_welcome4-01.wav": "1tsy8GxRU_G--PonhaB40X5VG9NwoZ7dJ",
  "Rosanna_W_voice_kr_welcome3-02.wav": "1yQgT9zhqOSCdtb3uhW928F3iNs4jaipb",
  "Rosanna_W_voice_kr_victory3-01.wav": "16U8f2o1_CAhCEwz5t-6SCxtKZH2RcMC4",
  "Rosanna_W_voice_kr_victory2-01.wav": "1Vc1Kfmss4TgLzr3KOOinSkWzsUn0iQ43",
  "Rosanna_W_voice_kr_victory6.wav": "1hkHRtvwDvJX0ktMoMiql6Fk1vjVKEArS",
  "Rosanna_W_voice_kr_victory5_02.wav": "1xBr1_JMP8NW2XO1Wq1fxmaJU2VmDBXjS",
  "Rosanna_W_voice_kr_victory4.wav": "1zL0QGXT9l3zR-Q8OZxhGfLzD-X2Q3eTj",
  "Rosanna_W_voice_kr_title-05.wav": "1LnYcy3XJqBITfYhLggAcaltag50e0sTD",
  "Rosanna_W_voice_kr_think-02.wav": "1NSZ0w9SZFzhTyP7bw1ZdA4ViNWAjz4u0",
  "Rosanna_W_voice_kr_victory1-01.wav": "1XoZc0fOKYR_IGQdE3NFCwKckn86lPuYa",
  "Rosanna_W_voice_kr_think-04.wav": "1eCM29B0GtR3XQdtcxEuvqyGLqgMNidj9",
  "Rosanna_W_voice_kr_think-06.wav": "1jfZGuCfwYiZc9Y1qlUGqfrQFlc_dDMhY",
  "Rosanna_W_voice_kr_surprised1-09.wav": "1mFVcRRRWBZTJD5C8LxdUmGatx_hxx7Uc",
  "Rosanna_W_voice_kr_speak8-02.wav": "1-bomAnlCb1TKZMkWuQU55PiDZSfzu6qt",
  "Rosanna_W_voice_kr_surprised1-08.wav": "141e4wIw1tdxk8I8Czf8NwfwEb_T-WLg_",
  "Rosanna_W_voice_kr_speak9-01.wav": "1JoytYdg9481GXVaIWy4_C1eBeSLCFdsR",
  "Rosanna_W_voice_kr_surprised1-06.wav": "1MNnMvBqxtj1NUpCLOws5TaH4pvHXR1No",
  "Rosanna_W_voice_kr_speak7.wav": "1qVFB5wXJ0AmAXXuHlQtbDcPMKpyffWdj",
  "Rosanna_W_voice_kr_speak31_01.wav": "11XiKOv3OpV6xt-26oSs5XfEmkrO7nlK8",
  "Rosanna_W_voice_kr_speak4-01.wav": "14RU4X38eVu2nAN4BhGoRLIfrbt-tP14o",
  "Rosanna_W_voice_kr_speak6-01.wav": "1Jcs-x13O4Ge38yZCMjG9nAIJDrg93b9d",
  "Rosanna_W_voice_kr_speak32_01.wav": "1MZb8CzcI5HzeeYbtROJteNFbRXAdKTPg",
  "Rosanna_W_voice_kr_speak5.wav": "1YdEcrsdYHQAzOZ8L7qocslu8_noDxPnn",
  "Rosanna_W_voice_kr_speak3-01.wav": "1kVbPTlDQTABE9W2AujIE56MpTCWYRcCW",
  "Rosanna_W_voice_kr_speak28_01.wav": "14uIvs4Lph93wwx_mUTIpkuKTttf4ABOl",
  "Rosanna_W_voice_kr_speak27_01.wav": "1luThDcuD-vwAZqwok6BsyKCE5P4CaRII",
  "Rosanna_W_voice_kr_speak26_01.wav": "1nFnQDgZNNwqZ8pTtyjYEM8DIfh9PXu99",
  "Rosanna_W_voice_kr_speak30_01.wav": "1qOM6PYG1wrKCorGVdf0M1PWhe9my4wpD",
  "Rosanna_W_voice_kr_speak25_01.wav": "1qdaZU99eUPyv8FtZQG8pL6HEolPsu3hl",
  "Rosanna_W_voice_kr_speak29.wav": "1zse_TU5JgRxrPJ8G5CEPbw6jCo6WB58m",
  "Rosanna_W_voice_kr_speak23.wav": "16m8-3agrXtM8j9V3YRLMG3X5HIqe1N2P",
  "Rosanna_W_voice_kr_speak22.wav": "1Yeg0xV9vRh5CVV0jkwOVDtCBZYE1YI23",
  "Rosanna_W_voice_kr_speak24.wav": "1jjjBmYD6yNrFCrF-QrvqL4xYhHks6-3f",
  "Rosanna_W_voice_kr_speak20.wav": "1ke-V_Lv2URRCA7ARXq8kR4eAaj--DAZO",
  "Rosanna_W_voice_kr_speak2-01.wav": "1uvKkR65yMi659gzSkqUgNYXisQoSYmA6",
  "Rosanna_W_voice_kr_speak21.wav": "1wNSZM4JUfVmaT9083qr_42u67uKdnegS",
  "Rosanna_W_voice_kr_speak15.wav": "128FGfiyUdcMO83tmP_J_WcJT6DjDKQ76",
  "Rosanna_W_voice_kr_speak14-01.wav": "1512YTdJvfguaKLPlm4HQzHs6VUkykjki",
  "Rosanna_W_voice_kr_speak17.wav": "1dWZr6QaJFg03iAkbn-TXifV9UN8wqwX_",
  "Rosanna_W_voice_kr_speak18_01.wav": "1dcalQ_dcHNB6pvAQW_YZQoBI-sOTnEBB",
  "Rosanna_W_voice_kr_speak16.wav": "1iuEFUxAf3R0C9_l2PqDBvq3WNnj9N6B9",
  "Rosanna_W_voice_kr_speak19_01.wav": "1q8T2-dTEIDr9ju_35iOZrUy3qhy66BFu",
  "Rosanna_W_voice_kr_speak10-01.wav": "179UdBaYfJFI8dm1IAnKYOhxkJyfIVmDP",
  "Rosanna_W_voice_kr_speak1-01.wav": "1ACtOb4RJCy10KoPDokJL1RdaKdJQ25AX",
  "Rosanna_W_voice_kr_speak13-01.wav": "1CrcrdPvbnP7km7vzqNTDVp0DKcds0OBu",
  "Rosanna_W_voice_kr_skill8-01.wav": "1HPGfJ6scW9ryqnQIMAaqjIbX8gGf2QDH",
  "Rosanna_W_voice_kr_speak11.wav": "1bzP8PIDN6zEl5eqDncw9i1i0dnUSEGjm",
  "Rosanna_W_voice_kr_speak12.wav": "1e76MhoWHgrZjmQBTHWYytUs0Jc1a4K90",
  "Rosanna_W_voice_kr_skill6.wav": "19Wb-NktLsRZsVLb2cxR-NV-TLHyv7W3G",
  "Rosanna_W_voice_kr_skill4-02.wav": "1AxAkjGmiaA06JVTOvtXcHgn-_hCC-Ag8",
  "Rosanna_W_voice_kr_skill5-01.wav": "1iGdWZB5CC89gea6K5jAjjCEkaN09EAZx",
  "Rosanna_W_voice_kr_skill3-01.wav": "1iddtJVQjkehAEYhaNqErQZB1P9nWtQmB",
  "Rosanna_W_voice_kr_skill7-02.wav": "1pySi92aOb7G7L9pAnKRrUKyotAmwXD2q",
  "Rosanna_W_voice_kr_skill3_ready2.wav": "1GfAcQcFWjH1OWDv5eqSBeExYvBcZdD8C",
  "Rosanna_W_voice_kr_skill3_ready3.wav": "1IpfWk-ZvsYjFKAnYqbDMGVS2BzM22krQ",
  "Rosanna_W_voice_kr_skill3_ready_up.wav": "1MAo8s7m339ZDlZXaN6lXS4oqnjzvwaaG",
  "Rosanna_W_voice_kr_skill3_smile.wav": "1_ttAQsPznKhU2CmFKq_DdHvcVRSenmDf",
  "Rosanna_W_voice_kr_skill3_ready1.wav": "1fPch-cvgHjG8_57u2ru2617qXIJNyf1A",
  "Rosanna_W_voice_kr_skill3_fire2.wav": "1jtx9d6sTjHrJnrNQcufMRg6bCnOJ9BHS",
  "Rosanna_W_voice_kr_skill3_fire1.wav": "12gFfn4CdtZrKSfGRVPlLoqbNDW1wo_5s",
  "Rosanna_W_voice_kr_skill3_5_1.wav": "1DuYcN12jQuU72P3oCn9tWs0yX4vrjTL5",
  "Rosanna_W_voice_kr_skill3_fire_down.wav": "1Hk9A2yeeaAP5iliVr68tEtLyVA56NINZ",
  "Rosanna_W_voice_kr_skill3_6_2.wav": "1NpZURW8qD6I-dvR2sXUDY6X1Mc_YR2VY",
  "Rosanna_W_voice_kr_skill3_6_1.wav": "1O-fpyE7jAVZQvUzVjoGP392OFzKFOsTd",
  "Rosanna_W_voice_kr_skill3_5_2.wav": "1O6iI2JWK-iBQ27iSv4JHnpqoK9DKmkEI",
  "Rosanna_W_voice_kr_skill3_2_2.wav": "12xYGanYu7zsxbCaCPfWXzQ6oGDlDnLE7",
  "Rosanna_W_voice_kr_skill3_3_1.wav": "156D-A8Ppgbh-mEB62E6NOylE67Lz8rXt",
  "Rosanna_W_voice_kr_skill3_4_2.wav": "1_IijEj292hStW3yLiYU-wQk_Q4kHgCIA",
  "Rosanna_W_voice_kr_skill3_4_1.wav": "1lb7F8wqZa1R0bN8g-xehl_hCT4CNhp90",
  "Rosanna_W_voice_kr_skill3_3_2.wav": "1mkMCoL2D2ovJoTK1HAaSoQSlvX32SLii",
  "Rosanna_W_voice_kr_skill3_2_1.wav": "1yxGPUMhCKFNGzESStoYbJ313Onro4cRx",
  "Rosanna_W_voice_kr_skill2-01.wav": "1gJZvODRMuqL7sCTHr7I47rT6mydGzSjB",
  "Rosanna_W_voice_kr_skill3_1_1.wav": "1h7AysMOiSyp5OLv2f_vkl8DXU7a1FIrB",
  "Rosanna_W_voice_kr_skill3_1_2.wav": "1mXjf4Oks2Q9-73-ITZFy1mdUc26A1F6u",
  "Rosanna_W_voice_kr_skill2_1_01.wav": "1nAxGsSXqHq5S4sB7rzCdSDt3Tst_shCw",
  "Rosanna_W_voice_kr_skill2_2_01.wav": "1ywa-If_jfwYR8B3mFuXONzfm46nVp01q",
  "Rosanna_W_voice_kr_sad1-06.wav": "15-9I8OKvX11C6DW49qZ9anbkJDE0D10J",
  "Rosanna_W_voice_kr_sigh-09.wav": "1BvrzMJ7SU2usIMmch9nb-7Z6SeE8Fy0I",
  "Rosanna_W_voice_kr_sigh-01.wav": "1DP3FhdD40EwGSoFSN6spM3A3xwtHq8WF",
  "Rosanna_W_voice_kr_sad1-10.wav": "1OQX5wKK0KzcpmzDrrEr03eURTOGbuhGA",
  "Rosanna_W_voice_kr_skill1-01.wav": "1rSr3Nh07vNWF5DpVehDdTFyKhb05mCCz",
  "Rosanna_W_voice_kr_sigh-06.wav": "1wLyaAObiCm1Y0rwD9Lef6d9OahAv4hs7",
  "Rosanna_W_voice_kr_ready9_01.wav": "1-7Mfweu-BXL1bGU0wTfAquLF60PygqdO",
  "Rosanna_W_voice_kr_ready8.wav": "1H-0RdooMXBf4fIiR8_IPWzrcU-AzEjod",
  "Rosanna_W_voice_kr_recruit2-01.wav": "1RzRfkDJdMTpzd1aYoK7Gsjs_2r9CkfO2",
  "Rosanna_W_voice_kr_recruit3_05.wav": "1TipbfnVDqKU4_NlnUkrdMzHLSf1gPt2A",
  "Rosanna_W_voice_kr_recruit1-01.wav": "1_folhtqm_pNKa1VI_gD1xGU2DEbz30ru",
  "Rosanna_W_voice_kr_sad1.wav": "1vIiHvyZfw3gbDxWNYOnpEVxJo_IBOPkJ",
  "Rosanna_W_voice_kr_ready4.wav": "128_97bsxXKknxli7mzSgm_4Lbs4YEaZl",
  "Rosanna_W_voice_kr_ready6.wav": "19dIi4hpCKk2ktB5N4N05K-9nNLfIE0Vz",
  "Rosanna_W_voice_kr_ready3-01.wav": "1IBi-ILKA0f0QbMheXjFGjKT9ps70QQmo",
  "Rosanna_W_voice_kr_ready2.wav": "1LXFZiFj9vGwkdDFzolkWNdqRXnimgqfE",
  "Rosanna_W_voice_kr_ready7.wav": "1R1uP9o88iMRau59kCDYDb4hpSh4pnUjY",
  "Rosanna_W_voice_kr_ready5-01.wav": "1_nrVvMzbFzh7pOnFvrg70hrpl2Ee8qyl",
  "Rosanna_W_voice_kr_promote3-01.wav": "1K-uCZBbpUQ0FWvP8kyX3FnUqkdqn_tef",
  "Rosanna_W_voice_kr_promote4-01.wav": "1S8GN52-MdzJBABE23_dUovbUVhkkDzW7",
  "Rosanna_W_voice_kr_ready1-01.wav": "1UGb4VNWuMOUPu-eilacxXsPhYDjL952_",
  "Rosanna_W_voice_kr_promote2-01.wav": "1n-UfBhfYiBjXDIMTD-huYcmN4s6uS-Li",
  "Rosanna_W_voice_kr_promote1-01.wav": "1uLUcR23FJQasYzuKhIPvTTUbFVSldZiO",
  "Rosanna_W_voice_kr_promote5.wav": "1v2BB-ARMZPOqHeQrgV-gFRps46abPYHg",
  "Rosanna_W_voice_kr_negative1-06.wav": "11Al4aNp92Do8RjTaaZ2MToMTdtxTwqmP",
  "Rosanna_W_voice_kr_negative1-17.wav": "1BFDqaoOnkdKHB4izg2LiHfQLouquYMGr",
  "Rosanna_W_voice_kr_positive1-13.wav": "1Q5jv_VTbQNJVp2pg9r56M5DUoQmlZJW6",
  "Rosanna_W_voice_kr_positive1.wav": "1V1lEsrtDpdw1grL9WjHBIy9-ihycOvdQ",
  "Rosanna_W_voice_kr_negative1-16.wav": "1aGfZ1HF_C0mZNEVAy4KpkXTckBAOF76H",
  "Rosanna_W_voice_kr_positive1-12.wav": "1nTR5Kw9OiQd6UfBFroZpix1s3feNvLzo",
  "Rosanna_W_voice_kr_happy1-12.wav": "133pvDC5K2IwZlB71mzRVyTiRPYqzfT64",
  "Rosanna_W_voice_kr_happy1-01.wav": "19MJ1uNHSn9HujC983k1BER-7KuabjgDI",
  "Rosanna_W_voice_kr_formation3.wav": "1EG4gIs2S8jmLTiLh-1C-VSpmFNFB698V",
  "Rosanna_W_voice_kr_landing.wav": "1_S8LBRx_eCX78VFmGmaq3pklDqnJgMcm",
  "Rosanna_W_voice_kr_happy1-15.wav": "1aYHi98qz5DwJIT6e4A4wkO7cURKl-gYZ",
  "Rosanna_W_voice_kr_formation2.wav": "1tGdpU6XT4zv7Cfz4Z-PQwuT4HO8GZu0l",
  "Rosanna_W_voice_kr_defeat1.wav": "1MD8W4iEGp1lod8VLc-kW4mNcJo28EA3s",
  "Rosanna_W_voice_kr_defeat2_03.wav": "1NeOnPEXuyInU99jzylD4_TcA1_PGumPO",
  "Rosanna_W_voice_kr_defeat3_03.wav": "1Xt0NqIZuRSFApEX--chG60nOMpd5tU-0",
  "Rosanna_W_voice_kr_formation1.wav": "1bFz7tBL9EC8yBn-5bj-XVnT12df_n2uZ",
  "Rosanna_W_voice_kr_dead2_02.wav": "1dZ9F7MgDGtEJ-gPKNztXdQnCue-0UOEZ",
  "Rosanna_W_voice_kr_damage1-06.wav": "1M1Yh13vEuHXCDDCOLnPe6LgHzasD2-4Z",
  "Rosanna_W_voice_kr_damage1-05.wav": "1M72x3Ue7rjhAwZdTWRwSNYu77tFoC6wv",
  "Rosanna_W_voice_kr_dead.wav": "1NCRsQwr6AE6zItUcu_XNIBrTxmdkb93G",
  "Rosanna_W_voice_kr_damage1-15.wav": "1dZhdAFgpKB7VKIRhH_eo5JzBp3OJWNeH",
  "Rosanna_W_voice_kr_damage1-12.wav": "1kKetkw98JhZVnjLmC3qCWa0AApctpWtu",
  "Rosanna_W_voice_kr_damage1-03.wav": "1nnP2y1VwJzkYNC5_eGaHOGyxdsYzaX9S",
  "Rosanna_W_voice_kr_costume3.wav": "183GHI7GhWlieZFeWJ0bTRw25c7wb9_Mw",
  "Rosanna_W_voice_kr_costume2.wav": "1XTgC0Fm_VtvbhuKPQI1E3rRdGb_cI8q0",
  "Rosanna_W_voice_kr_costume5.wav": "1m75bhyWmrFNah8Tpn-iRIAJQ4UaGCOTc",
  "Rosanna_W_voice_kr_costume1.wav": "1nQ-AhMidQSngnGtAJ4WYuFs8E80k4t9I",
  "Rosanna_W_voice_kr_costume4_01.wav": "1rgGYmYYieKan4uLdz51q0RzpqCrB2GJ0",
  "Rosanna_W_voice_kr_company-01.wav": "1xok_4GhLzojtFYmXQxnH9Ky7H8JtutPL",
  "Rosanna_W_voice_kr_character7-01.wav": "1M0wJJadtLqX2a6NrGFBaUsphxEJOYXGZ",
  "Rosanna_W_voice_kr_character4-02.wav": "1OlPCw0pj6ixJiqQgr-c81xmzardmFEpa",
  "Rosanna_W_voice_kr_character6.wav": "1e2eLe_OohA896orVTEClFtguYcyCWQMA",
  "Rosanna_W_voice_kr_character5.wav": "1hU0ZupVbNE14TtZ6BQCKE5X0Hbcr8HAb",
  "Rosanna_W_voice_kr_character8-01.wav": "1iGy0HWf6hwbQizNf11I_KabGuV0q-0Mk",
  "Rosanna_W_voice_kr_character9.wav": "1r3Kbze4rGrWfoEe7w32VD8QIokOHo0f1",
  "Rosanna_W_voice_kr_character2.wav": "10wukD8OMD1w0kUW6KrYdpv3Pwl_hW541",
  "Rosanna_W_voice_kr_battlestart3_01.wav": "1NvjEhJHYLsJR6c4owoqwIujU20e81lFK",
  "Rosanna_W_voice_kr_battlestart2.wav": "1TogK1tb1H5vaf9NJOr2tHztWsvEexGZm",
  "Rosanna_W_voice_kr_character1-03.wav": "1bhFHGyIXFh8KXoFYjNV3MFoCoqn0sOiY",
  "Rosanna_W_voice_kr_character3-01.wav": "1jLj1kzWRCV6dudATVA53x8wphjFWnA4b",
  "Rosanna_W_voice_kr_battlestart1.wav": "1n5KGuflpGkcXlcPsxHUS7cme_aYrFJRt",
  "Rosanna_W_voice_kr_awake1-05.wav": "14VBpmwAF8zsztJJQ7nuWmScnBcXbcFZT",
  "Rosanna_W_voice_kr_attack2-05.wav": "1ImePbZBGCaWgdfFJDlfE2pr9RQW1hGT3",
  "Rosanna_W_voice_kr_attack1-10.wav": "1P-8JQ0zhm0p1nx_I2rty77DkfNA6HBSo",
  "Rosanna_W_voice_kr_awake2-02.wav": "1k6bFd-gRFSlAMA2mRh_inA55mAqmt_SC",
  "Rosanna_W_voice_kr_awake4.wav": "1lPEJUfQ-PA7PkIyK0W8AZgnwsNf3_RD4",
  "Rosanna_W_voice_kr_awake3-03.wav": "1pWQEaHM8o9lZyW2uJlZSMDYlr8j_rpDd",
  "Rosanna_W_voice_kr_assist7_01.wav": "1-1hQgYdHHSLTKMbQJoo-Dw1-DLzlw-6B",
  "Rosanna_W_voice_kr_attack1-03.wav": "1Hhd01UHgmcqiB9zfB7Lw6LOXXeEc1RbT",
  "Rosanna_W_voice_kr_assist8_01.wav": "1JXD6K2SxlS34V8aOe1oNfD3ddN7oXkuL",
  "Rosanna_W_voice_kr_attack1-02.wav": "1TGhXK4dEBU7Kyl2KYEr1OqJ-yeLeeQCb",
  "Rosanna_W_voice_kr_attack1-07.wav": "1v3qxmsMEnXyLPJHTiSqgBRybEQ-R0W4R",
  "Rosanna_W_voice_kr_assist2-01.wav": "10SajPZLUWEe8KctVb48tw7lRnDra5M-q",
  "Rosanna_W_voice_kr_assist1.wav": "18DRhr4QKWsvgVFoj9wYI_p4oOS-87OV0",
  "Rosanna_W_voice_kr_assist6.wav": "1MFMmKUNwmP3vui63sJVMQBsldKXMDRGz",
  "Rosanna_W_voice_kr_assist3-06.wav": "1V2TpmmHNFOdIfWZHl_erZFaPoHDQWTSl",
  "Rosanna_W_voice_kr_assist5_01.wav": "1nXnA252VEOKhKk3OaAVBduymWsWWJ3pj",
  "Rosanna_W_voice_kr_assist4-03.wav": "1w7J_eajQALY6vlvmXwb9CkXcTGhSueCp",
  "Rosanna_L_voice_kr_victory2_01.wav": "19iUAeQrckrQrr17ZRzrI01f0qliJUtpq",
  "Rosanna_L_voice_kr_speak9.wav": "1D_ijcQEo8TV-sD_Fdnh2YthfEkbp8dd3",
  "Rosanna_L_voice_kr_speak7.wav": "1LneEWasrFQc5C523wZ8Rh-ct_QpNk1_J",
  "Rosanna_L_voice_kr_speak6.wav": "1QmxgJa0_loniNkvNHbhWZaanVn1DhGNg",
  "Rosanna_L_voice_kr_speak8.wav": "1TPwMb7TUKn-whMyRoySsfvZ4HRrH9zXp",
  "Rosanna_L_voice_kr_victory1.wav": "1W0h3iI4fQNY65MePkl-WaiZH0pu3nOr9",
  "Rosanna_L_voice_kr_speak2.wav": "12ypkkk3nAcc-CSgCXAuLuF2Vn00ZK18e",
  "Rosanna_L_voice_kr_speak3.wav": "17DEdl7hiT5fgxWL5ABSyQCmc6RTzmI_l",
  "Rosanna_L_voice_kr_speak4.wav": "1C5wmhdGIhyDKK8ZRapd9ob7_DQq991H_",
  "Rosanna_L_voice_kr_speak14.wav": "1L9Kgr5k1xvEM5TzaeblTs2sLxHJc-8x0",
  "Rosanna_L_voice_kr_speak5_01.wav": "1QdmyhKAmFp_6_XZJpuHsAaT7Ywo7C7Hu",
  "Rosanna_L_voice_kr_speak15.wav": "1toChqtIaGLNoGpHwuYANF2_b8wghRs3k",
  "Rosanna_L_voice_kr_speak12.wav": "16aVYp4YlSnHG6wDqKRIt03wqkJgFgnYT",
  "Rosanna_L_voice_kr_speak10.wav": "1B3QFqX_20sCSjDlKGZH1u3ov79UZ4CEP",
  "Rosanna_L_voice_kr_speak11.wav": "1dZByjzr1fFbt83tS7jpffK4l7lxidatL",
  "Rosanna_L_voice_kr_speak1.wav": "1hPkTl58VsvrvbEseyGUlbmbc53k-IflN",
  "Rosanna_L_voice_kr_skill3_2_2.wav": "1jTg-C2-25tGr94T3XJ-HrUsYi5wy8SpO",
  "Rosanna_L_voice_kr_speak13_01.wav": "1memRVciyaaB2Jk-vPrxQoIxjEx04Aw3J",
  "Rosanna_L_voice_kr_skill3_1_1.wav": "15W06Qz4c6upuJMpJ1tGlT3ZpsMeHf25Y",
  "Rosanna_L_voice_kr_skill3_2_1.wav": "1WD1fK-qKNg2cjrlrJ29Hvx8g1YmIi6ir",
  "Rosanna_L_voice_kr_skill2_1.wav": "1_C51vIbS4HNQBXPf8SIsyOXOsymkqGeX",
  "Rosanna_L_voice_kr_skill2_2_01.wav": "1h1MlDNmbxb7cehU2xdDviXOULa5SUXNQ",
  "Rosanna_L_voice_kr_skill3_1_2.wav": "1nvriNqN8XxyoIcoRxsVocC7LrYFo6MEP",
  "Rosanna_L_voice_kr_recruit_01.wav": "18j2kcHTowKXQredzhCIIQhD7QBV7TvEa",
  "Rosanna_L_voice_kr_ready2_01.wav": "1fCnN5iLZ3JHtrmTzrM1jR695urGILFc0",
  "Rosanna_L_voice_kr_ready3_01.wav": "1hy4cvqADlGoaxrdHtn5PVazK9UHegxdS",
  "Rosanna_L_voice_kr_promote.wav": "1q_f9QpLQokUqpLaOqgBH5FlFhI99Hf2y",
  "Rosanna_L_voice_kr_ready1.wav": "1tGETgcyN4G7m5C3T9x69Ch7uHv_4Zsmu",
  "Rosanna_L_voice_kr_dead_01.wav": "1xgov0bkxBbD_6_VcCsDVIwPH0jFn1rOy",
  "Rosanna_L_voice_kr_assist2.wav": "1H_xTqc5jlKBeDD13aKFdjLB9jBze6orv",
  "Rosanna_L_voice_kr_assist3.wav": "1RitNoYJm8WFybSZI_Sq38a0GwexLRRBR",
  "Rosanna_L_voice_kr_awake.wav": "1T8QX5cCXRiojXYKWWbtshffj-MLm-ZwS",
  "Rosanna_F_voice_kr_victory2.wav": "1d8BKahiBbd_Q4edMB1jMkGIfVOP7yumY",
  "Rosanna_L_voice_kr_assist1.wav": "1fSEU1FgcaaMMmQMCx-MiW--1cXHmnKne",
  "Rosanna_L_voice_kr_assist4_01.wav": "1kIph9bVFGbHBlFgstx58AygvdjNL6lzV",
  "Rosanna_F_voice_kr_victory1_01.wav": "18W2FSXs7psXbE9MzPBuUy0fsX5OvmvNF",
  "Rosanna_F_voice_kr_speak5.wav": "13IJLaSAyA01Em7fyQi43IkTQD5FTlCf0",
  "Rosanna_F_voice_kr_speak6.wav": "1REY3dFtaEvfGW0sHc1elIB9ofd_Dqd6q",
  "Rosanna_F_voice_kr_speak9_01.wav": "1WItO0EE8ksUMPw6xwWkODedE-WB841VX",
  "Rosanna_F_voice_kr_speak7_02.wav": "1b05BXfGLAxrMfBUIkNAHnRNtQ-Jqtr6d",
  "Rosanna_F_voice_kr_speak8_01.wav": "1sIY5eQeJUBoV0Ni48IaHUVqNTaFHhARh",
  "Rosanna_F_voice_kr_speak3_01.wav": "1Alu7XSLPyv4TziIAbOzMoeEl_f_i0fAU",
  "Rosanna_F_voice_kr_speak15_01.wav": "1D_vz2E8qSaqAsuSJ-CP7vwxtt3T47e_B",
  "Rosanna_F_voice_kr_speak4_02.wav": "1__usB3w9WVxzsyVBkMSn-8PBotvv0ElM",
  "Rosanna_F_voice_kr_speak13.wav": "1cxyw4Y1oU1ZVDtvDFKWGur_zyJymyWfG",
  "Rosanna_F_voice_kr_speak14_02.wav": "1gsGHZp_QmWgP0S3v2Q-wMuBi7xAwquN-",
  "Rosanna_F_voice_kr_speak2.wav": "1pu9bCw3BxZ-UBSn10iicaJjkyM2dGEqs",
  "Rosanna_F_voice_kr_speak10_01.wav": "1CgQMF1w_AFiIE1F7qqtu-c9U43mr37_T",
  "Rosanna_F_voice_kr_speak12.wav": "1CupooIj1QbAnkbSFYtbbU2Hz3VAFNpgO",
  "Rosanna_F_voice_kr_skill3_2_2.wav": "1Oek9XzlKKZFFNWq3dSAlDJnpCyhfZDiT",
  "Rosanna_F_voice_kr_speak11_01.wav": "1PTvQTPptgSEZS8fSZ6LYAfd2vtpeML6T",
  "Rosanna_F_voice_kr_speak1_01.wav": "1Z0--JnwHgIR3vbWoMKVMB28JeGnuRZFr",
  "Rosanna_F_voice_kr_skill3_2_1.wav": "13PuWTOj9z1GAEImjLiE6WxxTMsUTQ8_I",
  "Rosanna_F_voice_kr_recruit_01.wav": "1MViU2YdOyLRYHtO13CMShIkwBq6mTdva",
  "Rosanna_F_voice_kr_skill2_1.wav": "1QcsMkoJBJOyMrgQ5bm2Sn-HUW2fPx0gx",
  "Rosanna_F_voice_kr_skill3_1_2.wav": "1Sfl8EVmtUgNqBvETRIFXYG7ZggVHv574",
  "Rosanna_F_voice_kr_skill3_1_1.wav": "1UyXY12pYy0Xczk_J1_QUDteODzTAIN9p",
  "Rosanna_F_voice_kr_skill2_2.wav": "1ihcUHLYTPGb-AVQF_Ufu1Yg9H5bONz1f",
  "Rosanna_F_voice_kr_promote_01.wav": "1CNX8wv1wTAaONK75ZPabP2fHHq4uTza3",
  "Rosanna_F_voice_kr_ready2.wav": "1HxG2FPx9lY_trpy-TKPwVrhp0VlMyp1X",
  "Rosanna_F_voice_kr_ready3_01.wav": "1g4aR94DDrk9QBUUB047nfrSTAzzPFHOT",
  "Rosanna_F_voice_kr_ready1.wav": "1ke6xQPWeGLO0wtiG-OBGqyvIFp_Ig4a0",
  "Rosanna_F_voice_kr_dead.wav": "1lNjO96rSW7yDCUeTgydJfreD3GPUPvh7",
  "Rosanna_F_voice_kr_awake_01.wav": "1ob3R36TuELBRlDLdWYLA35elP8XT9JrM",
  "Rosanna_F_voice_kr_assist3_01.wav": "14yH-5by60PMTNkZrc7m74kzdWnfRkhsM",
  "Rosanna_E_voice_kr_victory2_01.wav": "1CSD5EQXbZ9bBnsKIaMM7t6EO5H_S1EC3",
  "Rosanna_F_voice_kr_assist2_01.wav": "1FLDobxi5OO3FRGJt_Tk8kPWGRcjpjFSZ",
  "Rosanna_F_voice_kr_assist1_01.wav": "1_N6w_ID4UqwvCYBB0-gR0_YXFfN-HI4k",
  "Rosanna_F_voice_kr_assist4_01.wav": "1cvVEodMyVJyXfP9hBd5buNWhHteLlfZt",
  "Rosanna_E_voice_kr_victory1.wav": "1jDHDBqDDNTzYywutSG49Db6bGgIUX5Dx",
  "Rosanna_E_voice_kr_speak8.wav": "1X9rru72oi9MpNi9bLuLDX3sclpyCusrk",
  "Rosanna_E_voice_kr_speak7.wav": "1_AXjVfFnuAxZW9DB16m64Bx8l2YgRr4x",
  "Rosanna_E_voice_kr_speak6.wav": "1b4WVn0G2AUrMd7Hu2XNM6613WD95iQF2",
  "Rosanna_E_voice_kr_speak9.wav": "1bVWTMP7GSZalPIt53BnNsLq09PbmSDJr",
  "Rosanna_E_voice_kr_speak4_01.wav": "1ewa-HWtbNKLULn4Z_gNSr8wzY1Vr3HVr",
  "Rosanna_E_voice_kr_speak5.wav": "1oG3A7_O8LKeZtZ6SFtOAJjVVFDkGxgUg",
  "Rosanna_E_voice_kr_speak14.wav": "11jyU5zlX2zck7rHU2c7CmzOhTQVp2Cle",
  "Rosanna_E_voice_kr_speak13.wav": "11w-sNp-lJIbdtIqg7tCtrflqxwg7Bj-D",
  "Rosanna_E_voice_kr_speak15.wav": "1V38pz6Y00CdsE2ykVJdTT77Jx6dohXxF",
  "Rosanna_E_voice_kr_speak3.wav": "1jRvJh7Z4tHVzlFPNxiGcGzLyS3og1-FJ",
  "Rosanna_E_voice_kr_speak2.wav": "1ovdF5gxe3FBZ4ak1hiGGFiIRttmbnyX4",
  "Rosanna_E_voice_kr_speak10.wav": "1-ltIGEzW9bsQcy3JjJf2tZ7kCbkHPXjg",
  "Rosanna_E_voice_kr_speak11.wav": "1GhtCN0UFBA682J7ClocDq8VP80qQIfH-",
  "Rosanna_E_voice_kr_skill3_2_2.wav": "1KpuoSavmn1qLwZ9yj6JUqADcGirFJyzI",
  "Rosanna_E_voice_kr_speak1_01.wav": "1V0lv-yGmkMVyFdjMDraxQ1esov7127Jb",
  "Rosanna_E_voice_kr_skill3_2_1.wav": "1Vz6bOVZ5YgZ8JVHB7yeHaUrAliDOMSKz",
  "Rosanna_E_voice_kr_speak12.wav": "1XGVr5-ZN4bTDMdl_UXtqx7x0kqLNSCaF",
  "Rosanna_E_voice_kr_skill3_1_2.wav": "12ctQiuAFFxQhy1Ck00aRA8JPrdTPGG6N",
  "Rosanna_E_voice_kr_recruit_01.wav": "13-_HoU-uGrZudxSvSdNqsqrg5hWJi-aA",
  "Rosanna_E_voice_kr_skill3_1_1.wav": "1Bh2aNVCjE8cveO_Eyw4k0e9jC82e4BO-",
  "Rosanna_E_voice_kr_skill2_2.wav": "1bvxlCrnixlkL7hT6R72nGI2ft-dGhqN1",
  "Rosanna_E_voice_kr_ready3_01.wav": "1gTKGJdE_iTQYsQmafcbDCv3xsJVCRirW",
  "Rosanna_E_voice_kr_skill2_1.wav": "1iWlYj0Zt_BhFjHa2CSHV91nGu9sQwpoA",
  "Rosanna_E_voice_kr_ready2_01.wav": "17hB_DDkoZTLNRyGqulelVpuBUC-GP2rl",
  "Rosanna_E_voice_kr_awake.wav": "1ByLOxev3FawoXTNohnb1D2xE3THUGXXn",
  "Rosanna_E_voice_kr_dead.wav": "1VqagymQ6KamwJknXmxX3xkLdGJbudKnm",
  "Rosanna_E_voice_kr_promote.wav": "1diioN6E8M33F_-cEmkBZ85s7wNxat9_O",
  "Rosanna_E_voice_kr_assist4.wav": "1pQ-T7_aBSnds0UhlwQrZq1qejbimNxI_",
  "Rosanna_E_voice_kr_ready1.wav": "1tMnp62MDZoJGKC-9WTQq_QJ77yygpTTQ",
  "Rosanna_D_voice_kr_victory1_01.wav": "1FdpmLiXE5WEQc9OJLOsq4D8pqGpQMFHq",
  "Rosanna_E_voice_kr_assist1_01.wav": "1aP8eCYONMipbUFFFF8a2dj_dpdsdU4Ul",
  "Rosanna_E_voice_kr_assist3_01.wav": "1fF_7NgJ0WwJBp0R7dcEQL8wOMLK_cvi-",
  "Rosanna_E_voice_kr_assist2_01.wav": "1o8NRI8FdlSUJ3_09CwqwMyUvjRYIlYWf",
  "Rosanna_D_voice_kr_victory2_04.wav": "1uN3VNn_Tj4fwom9Qqn4S6buZCq8v4woV",
  "Rosanna_D_voice_kr_speak9.wav": "15LLgkFrVX6haOd4i4NzV7FR222xo2e4v",
  "Rosanna_D_voice_kr_speak4_01.wav": "1EoOjfIrLh7WYx8ou-Hq-AAOWgLIOGMj9",
  "Rosanna_D_voice_kr_speak5.wav": "1J2TPTXjiAfqaToplo2oSFrMc6o15OaqR",
  "Rosanna_D_voice_kr_speak6_01.wav": "1JPJpnYN6xDxdPN4QPvmxtFXUQdEYL_Ya",
  "Rosanna_D_voice_kr_speak7_01.wav": "1pCcdV8K-43MnCfAELxhjH-ikw7YAZQyj",
  "Rosanna_D_voice_kr_speak8_02.wav": "1sB0Q7i-TQN6qMWBBa4a6KlEWcs2gN-Uq",
  "Rosanna_D_voice_kr_speak15_02.wav": "117YcG2BlZ6x7A1KqywZX9gh_JxZ02fbU",
  "Rosanna_D_voice_kr_speak3.wav": "1M31ChV2x_7tI9btms04Nai45I9R8m2Kv",
  "Rosanna_D_voice_kr_speak12.wav": "1isxiGyNoyY0ou_5wnYfd1b7Dy4GEXFaV",
  "Rosanna_D_voice_kr_speak14_01.wav": "1mE2DW60-aO3qGxDXuUcKJr6ZeKnql-4A",
  "Rosanna_D_voice_kr_speak2_01.wav": "1pC5jGePp_cZ97C8Oh2Wr6M8KzbmnPDLQ",
  "Rosanna_D_voice_kr_speak13.wav": "1tdgp8DAspRGNBUORl2UMBvBJ4d35MOKX",
  "Rosanna_D_voice_kr_skill3_1_2.wav": "12Kku3L_Uo9V2svqdsMnUcmbIljzLS7Po",
  "Rosanna_D_voice_kr_skill3_2_2.wav": "14seYsrwiwBogj3HMa76u-fblqRCgYXTP",
  "Rosanna_D_voice_kr_skill3_2_1.wav": "1HEb1HhfYjsl4OwuF4kVVjq_LBN-0lwOd",
  "Rosanna_D_voice_kr_speak1_01.wav": "1WKR1exQCj2Kvin3rBpbT5-D4_ECH8YE7",
  "Rosanna_D_voice_kr_speak10_01.wav": "1yP1zVjE_eT7vq_eFt1Y9ZUWrwd2jZFV7",
  "Rosanna_D_voice_kr_speak11_01.wav": "1zYHgWE38OQDTTbyoiN9bZnxwDifsIVCn",
  "Rosanna_D_voice_kr_skill3_1_1.wav": "18c_5Qj7GETGlCGFS9yoYEagnTdHsUMKK",
  "Rosanna_D_voice_kr_skill2_1.wav": "1BNZQrGMNC7vVv0LtCesMHijbmi_kSejG",
  "Rosanna_D_voice_kr_recruit_01.wav": "1Bh8ANZ86Yt17fpfEVmqzE6LgtT_zoS0-",
  "Rosanna_D_voice_kr_ready3.wav": "1E1mkphCWNY9HKQKlwhdURR5GQWtq1VUA",
  "Rosanna_D_voice_kr_skill2_2.wav": "1gz4kKzfcEb-pIIOdvI7d1XdJSc7FrDzP",
  "Rosanna_D_voice_kr_awake.wav": "1MFeh0wMWYbUWQkE4q0D702LtlFeWjGCN",
  "Rosanna_D_voice_kr_dead_01.wav": "1SjYFLrlbfZ0FMLu2KkM5VFWIjoJc-UmP",
  "Rosanna_D_voice_kr_ready1_01.wav": "1jzw44w-LdMvdRIgg6u9-n0kPE_MrAOEg",
  "Rosanna_D_voice_kr_ready2.wav": "1kZ5TPpKqutPoqjgmtvYyIbEs8Nfg6Qrs",
  "Rosanna_D_voice_kr_promote.wav": "1npYV8Jg2iArJk3KLujs69cXjvfPrt6KD",
  "Rosanna_D_voice_kr_assist4_03.wav": "1u83f24qMkLrPgBfAJvoqq9YjaOyhF-LU",
  "Rosanna_D_voice_kr_assist1_03.wav": "1EczFsgyfESM647aT5Tgr-FAwdTxb0Fqz",
  "Rosanna_D_voice_kr_assist2_02.wav": "1jE2PyXMcBscwpEG6EkUKlFx0cih7aS9Q",
  "Rosanna_D_voice_kr_assist3_02.wav": "1sxZVPbTVsyXW5EAFXjd9-cPapT7oXmDy"
};

// 드라이브 직링 변환 함수 (이미지/보이스 공용)
function getDriveUrl(fileName, type = 'image') {
  const id = (type === 'image') ? driveImageMap[fileName] : driveVoiceMap[fileName];
  if (!id) return ''; // ID가 없으면 빈값
  
  // 구글 드라이브 직링 포맷
  return `https://docs.google.com/uc?export=download&id=${id}`;
}

// data.js - 데이터 전용 파일

// 1. 아이템 리스트
const itemList = [
    "icon_BiancaBeautyDollA1.png", "icon_HelgaBeautyMinishipA1.png", "icon_RicardoBeautyDollB1.png",
    "icon_RicardoBeautyYoungrosannadollA1.png", "icon_RosannaBeautyBdayA1.png", "icon_RosannaBeautyBdayA2.png",
    "icon_RosannaBeautyBdayA3.png", "icon_RosannaBeautyBdayA4.png", "icon_RosannaBeautyBdayA5.png",
    "icon_RosannaBeautyBdayB1.png", "icon_RosannaBeautyBdayB2.png", "icon_RosannaBeautyBdayB3.png",
    "icon_RosannaBeautyBdayB4.png", "icon_RosannaBeautyBdayB5.png", "icon_RosannaBeautyChinchillaearsA1.png",
    "icon_RosannaBeautyChinchillaearsA2.png", "icon_RosannaBeautyChinchillaearsA3.png", "icon_RosannaBeautyChinchillaearsA4.png",
    "icon_RosannaBeautyChinchillaearsA5.png", "icon_RosannaBeautydollEA1.png", "icon_RosannaBeautyGlassesA1.png",
    "icon_RosannaBeautyGlassesB1.png", "icon_RosannaBeautyGlassesC1.png", "icon_RosannaBeautyGlassesD1.png",
    "icon_RosannaBeautyGlassesE1.png", "icon_RosannaBeautyGlassesE2.png", "icon_RosannaBeautyMinishipA1.png",
    "icon_RosannaBeautyMinishipB1.png", "icon_RosannaBeautyMinishipC1.png", "icon_RosannaBeautyPearlpinA1.png",
    "icon_RosannaBeautyPearlpinA2.png", "icon_RosannaBeautyPearlpinA3.png", "icon_RosannaBeautyPigeonA1.png",
    "icon_RosannaBeautyStarearingA1.png", "icon_RosannaBeautyStarearingA2.png", "icon_RosannaBeautyStarearingA3.png",
    "icon_RosannaBeautyStarearingA4.png", "icon_RosannaBeautyStarearingA5.png"
];

// 2. 갤러리 리스트
const galleryList = [
    "bday_sd_dark_rosanna_illust.png", "bday_sd_fire_rosanna_illust.png",
    "photocard_bday_rosanna_dark_illust.png", "photocard_bday_rosanna_light_illust.png",
    "photocard_bday_rosanna_water_illust.png", "photocard_sidestory_mu_rosanna_illust.png",
    "shop_chuseok2025_illust.png", "shop_earlysummer2024_illust.png",
    "shop_holiday2021_illust.png", "shop_newyear2025_illust.png", "shop_summer2021_illust.png"
];

// 3. 캐릭터 설정
const charConfig = {
    elements: {
        'D': { name: 'Dark',   full: 'dark',  icon: 'RosannaD3_icon.png' },
        'E': { name: 'Earth',  full: 'earth', icon: 'RosannaE3_icon.png' },
        'F': { name: 'Fire',   full: 'fire',  icon: 'RosannaF3_icon.png' },
        'L': { name: 'Light',  full: 'light', icon: 'RosannaL3_icon.png' },
        'W': { name: 'Water',  full: 'water', icon: 'RosannaW3_icon.png' }
    },
    evolution: {
        'D': [ {id:'D1', s:'D1'}, {id:'D2', s:'D2'}, {id:'D3', s:'D3'} ],
        'E': [ {id:'E1', s:'E1'}, {id:'E2', s:'E2'}, {id:'E3', s:'E3'} ],
        'F': [ {id:'F1', s:'F1'}, {id:'F2', s:'F2'}, {id:'F3', s:'F3'} ],
        'L': [ {id:'L1', s:'L1'}, {id:'L2', s:'L2'}, {id:'L3', s:'L3'} ],
        'W': [ {id:'W1', s:'W1'}, {id:'W2', s:'W2'}, {id:'W3', s:'W3'} ]
    },
    costumes: {
        'W': [
            { id:'Summer21', s:'Summerwear2021W', icon:'RosannaSummerwear2021W_icon.png' },
            { id:'Summer21R', s:'Summerwear2021RareW', icon:'RosannaSummerwear2021RareW_icon.png' },
            { id:'Summer22', s:'Summerwear2022W', icon:'RosannaSummerwear2022W_icon.png' },
            { id:'Summer22R', s:'Summerwear2022RareW', icon:'RosannaSummerwear2022RareW_icon.png' },
            { id:'Holiday22', s:'Holidaywear2022W', icon:'RosannaHolidaywear2022W_icon.png' },
            { id:'Holiday22R', s:'Holidaywear2022RareW', icon:'RosannaHolidaywear2022RareW_icon.png' },
            { id:'Young', s:'YoungRosannaW2', icon:'YoungRosannaW2_icon.png', isSpecial: true }
        ]
    }
};

// 4. 보이스 파일 리스트 (여기에 299개 전체 리스트를 붙여넣으세요!)
const rosannaVoiceFiles = [
  "Rosanna_D_voice_kr_assist1_03.wav",
  "Rosanna_D_voice_kr_assist2_02.wav",
  "Rosanna_D_voice_kr_assist3_02.wav",
  "Rosanna_D_voice_kr_assist4_03.wav",
  "Rosanna_D_voice_kr_awake.wav",
  "Rosanna_D_voice_kr_dead_01.wav",
  "Rosanna_D_voice_kr_promote.wav",
  "Rosanna_D_voice_kr_ready1_01.wav",
  "Rosanna_D_voice_kr_ready2.wav",
  "Rosanna_D_voice_kr_ready3.wav",
  "Rosanna_D_voice_kr_recruit_01.wav",
  "Rosanna_D_voice_kr_skill2_1.wav",
  "Rosanna_D_voice_kr_skill2_2.wav",
  "Rosanna_D_voice_kr_skill3_1_1.wav",
  "Rosanna_D_voice_kr_skill3_1_2.wav",
  "Rosanna_D_voice_kr_skill3_2_1.wav",
  "Rosanna_D_voice_kr_skill3_2_2.wav",
  "Rosanna_D_voice_kr_speak10_01.wav",
  "Rosanna_D_voice_kr_speak11_01.wav",
  "Rosanna_D_voice_kr_speak12.wav",
  "Rosanna_D_voice_kr_speak13.wav",
  "Rosanna_D_voice_kr_speak14_01.wav",
  "Rosanna_D_voice_kr_speak15_02.wav",
  "Rosanna_D_voice_kr_speak1_01.wav",
  "Rosanna_D_voice_kr_speak2_01.wav",
  "Rosanna_D_voice_kr_speak3.wav",
  "Rosanna_D_voice_kr_speak4_01.wav",
  "Rosanna_D_voice_kr_speak5.wav",
  "Rosanna_D_voice_kr_speak6_01.wav",
  "Rosanna_D_voice_kr_speak7_01.wav",
  "Rosanna_D_voice_kr_speak8_02.wav",
  "Rosanna_D_voice_kr_speak9.wav",
  "Rosanna_D_voice_kr_victory1_01.wav",
  "Rosanna_D_voice_kr_victory2_04.wav",
  "Rosanna_E_voice_kr_assist1_01.wav",
  "Rosanna_E_voice_kr_assist2_01.wav",
  "Rosanna_E_voice_kr_assist3_01.wav",
  "Rosanna_E_voice_kr_assist4.wav",
  "Rosanna_E_voice_kr_awake.wav",
  "Rosanna_E_voice_kr_dead.wav",
  "Rosanna_E_voice_kr_promote.wav",
  "Rosanna_E_voice_kr_ready1.wav",
  "Rosanna_E_voice_kr_ready2_01.wav",
  "Rosanna_E_voice_kr_ready3_01.wav",
  "Rosanna_E_voice_kr_recruit_01.wav",
  "Rosanna_E_voice_kr_skill2_1.wav",
  "Rosanna_E_voice_kr_skill2_2.wav",
  "Rosanna_E_voice_kr_skill3_1_1.wav",
  "Rosanna_E_voice_kr_skill3_1_2.wav",
  "Rosanna_E_voice_kr_skill3_2_1.wav",
  "Rosanna_E_voice_kr_skill3_2_2.wav",
  "Rosanna_E_voice_kr_speak10.wav",
  "Rosanna_E_voice_kr_speak11.wav",
  "Rosanna_E_voice_kr_speak12.wav",
  "Rosanna_E_voice_kr_speak13.wav",
  "Rosanna_E_voice_kr_speak14.wav",
  "Rosanna_E_voice_kr_speak15.wav",
  "Rosanna_E_voice_kr_speak1_01.wav",
  "Rosanna_E_voice_kr_speak2.wav",
  "Rosanna_E_voice_kr_speak3.wav",
  "Rosanna_E_voice_kr_speak4_01.wav",
  "Rosanna_E_voice_kr_speak5.wav",
  "Rosanna_E_voice_kr_speak6.wav",
  "Rosanna_E_voice_kr_speak7.wav",
  "Rosanna_E_voice_kr_speak8.wav",
  "Rosanna_E_voice_kr_speak9.wav",
  "Rosanna_E_voice_kr_victory1.wav",
  "Rosanna_E_voice_kr_victory2_01.wav",
  "Rosanna_F_voice_kr_assist1_01.wav",
  "Rosanna_F_voice_kr_assist2_01.wav",
  "Rosanna_F_voice_kr_assist3_01.wav",
  "Rosanna_F_voice_kr_assist4_01.wav",
  "Rosanna_F_voice_kr_awake_01.wav",
  "Rosanna_F_voice_kr_dead.wav",
  "Rosanna_F_voice_kr_promote_01.wav",
  "Rosanna_F_voice_kr_ready1.wav",
  "Rosanna_F_voice_kr_ready2.wav",
  "Rosanna_F_voice_kr_ready3_01.wav",
  "Rosanna_F_voice_kr_recruit_01.wav",
  "Rosanna_F_voice_kr_skill2_1.wav",
  "Rosanna_F_voice_kr_skill2_2.wav",
  "Rosanna_F_voice_kr_skill3_1_1.wav",
  "Rosanna_F_voice_kr_skill3_1_2.wav",
  "Rosanna_F_voice_kr_skill3_2_1.wav",
  "Rosanna_F_voice_kr_skill3_2_2.wav",
  "Rosanna_F_voice_kr_speak10_01.wav",
  "Rosanna_F_voice_kr_speak11_01.wav",
  "Rosanna_F_voice_kr_speak12.wav",
  "Rosanna_F_voice_kr_speak13.wav",
  "Rosanna_F_voice_kr_speak14_02.wav",
  "Rosanna_F_voice_kr_speak15_01.wav",
  "Rosanna_F_voice_kr_speak1_01.wav",
  "Rosanna_F_voice_kr_speak2.wav",
  "Rosanna_F_voice_kr_speak3_01.wav",
  "Rosanna_F_voice_kr_speak4_02.wav",
  "Rosanna_F_voice_kr_speak5.wav",
  "Rosanna_F_voice_kr_speak6.wav",
  "Rosanna_F_voice_kr_speak7_02.wav",
  "Rosanna_F_voice_kr_speak8_01.wav",
  "Rosanna_F_voice_kr_speak9_01.wav",
  "Rosanna_F_voice_kr_victory1_01.wav",
  "Rosanna_F_voice_kr_victory2.wav",
  "Rosanna_L_voice_kr_assist1.wav",
  "Rosanna_L_voice_kr_assist2.wav",
  "Rosanna_L_voice_kr_assist3.wav",
  "Rosanna_L_voice_kr_assist4_01.wav",
  "Rosanna_L_voice_kr_awake.wav",
  "Rosanna_L_voice_kr_dead_01.wav",
  "Rosanna_L_voice_kr_promote.wav",
  "Rosanna_L_voice_kr_ready1.wav",
  "Rosanna_L_voice_kr_ready2_01.wav",
  "Rosanna_L_voice_kr_ready3_01.wav",
  "Rosanna_L_voice_kr_recruit_01.wav",
  "Rosanna_L_voice_kr_skill2_1.wav",
  "Rosanna_L_voice_kr_skill2_2_01.wav",
  "Rosanna_L_voice_kr_skill3_1_1.wav",
  "Rosanna_L_voice_kr_skill3_1_2.wav",
  "Rosanna_L_voice_kr_skill3_2_1.wav",
  "Rosanna_L_voice_kr_skill3_2_2.wav",
  "Rosanna_L_voice_kr_speak1.wav",
  "Rosanna_L_voice_kr_speak10.wav",
  "Rosanna_L_voice_kr_speak11.wav",
  "Rosanna_L_voice_kr_speak12.wav",
  "Rosanna_L_voice_kr_speak13_01.wav",
  "Rosanna_L_voice_kr_speak14.wav",
  "Rosanna_L_voice_kr_speak15.wav",
  "Rosanna_L_voice_kr_speak2.wav",
  "Rosanna_L_voice_kr_speak3.wav",
  "Rosanna_L_voice_kr_speak4.wav",
  "Rosanna_L_voice_kr_speak5_01.wav",
  "Rosanna_L_voice_kr_speak6.wav",
  "Rosanna_L_voice_kr_speak7.wav",
  "Rosanna_L_voice_kr_speak8.wav",
  "Rosanna_L_voice_kr_speak9.wav",
  "Rosanna_L_voice_kr_victory1.wav",
  "Rosanna_L_voice_kr_victory2_01.wav",
  "Rosanna_W_voice_kr_assist1.wav",
  "Rosanna_W_voice_kr_assist2-01.wav",
  "Rosanna_W_voice_kr_assist3-06.wav",
  "Rosanna_W_voice_kr_assist4-03.wav",
  "Rosanna_W_voice_kr_assist5_01.wav",
  "Rosanna_W_voice_kr_assist6.wav",
  "Rosanna_W_voice_kr_assist7_01.wav",
  "Rosanna_W_voice_kr_assist8_01.wav",
  "Rosanna_W_voice_kr_awake1-05.wav",
  "Rosanna_W_voice_kr_awake2-02.wav",
  "Rosanna_W_voice_kr_awake3-03.wav",
  "Rosanna_W_voice_kr_awake4.wav",
  "Rosanna_W_voice_kr_battlestart1.wav",
  "Rosanna_W_voice_kr_battlestart2.wav",
  "Rosanna_W_voice_kr_battlestart3_01.wav",
  "Rosanna_W_voice_kr_character1-03.wav",
  "Rosanna_W_voice_kr_character2.wav",
  "Rosanna_W_voice_kr_character3-01.wav",
  "Rosanna_W_voice_kr_character4-02.wav",
  "Rosanna_W_voice_kr_character5.wav",
  "Rosanna_W_voice_kr_character6.wav",
  "Rosanna_W_voice_kr_character7-01.wav",
  "Rosanna_W_voice_kr_character8-01.wav",
  "Rosanna_W_voice_kr_character9.wav",
  "Rosanna_W_voice_kr_company-01.wav",
  "Rosanna_W_voice_kr_costume1.wav",
  "Rosanna_W_voice_kr_costume2.wav",
  "Rosanna_W_voice_kr_costume3.wav",
  "Rosanna_W_voice_kr_costume4_01.wav",
  "Rosanna_W_voice_kr_costume5.wav",
  "Rosanna_W_voice_kr_dead.wav",
  "Rosanna_W_voice_kr_dead2_02.wav",
  "Rosanna_W_voice_kr_defeat1.wav",
  "Rosanna_W_voice_kr_defeat2_03.wav",
  "Rosanna_W_voice_kr_defeat3_03.wav",
  "Rosanna_W_voice_kr_formation1.wav",
  "Rosanna_W_voice_kr_formation2.wav",
  "Rosanna_W_voice_kr_formation3.wav",
  "Rosanna_W_voice_kr_promote1-01.wav",
  "Rosanna_W_voice_kr_promote2-01.wav",
  "Rosanna_W_voice_kr_promote3-01.wav",
  "Rosanna_W_voice_kr_promote4-01.wav",
  "Rosanna_W_voice_kr_promote5.wav",
  "Rosanna_W_voice_kr_ready1-01.wav",
  "Rosanna_W_voice_kr_ready2.wav",
  "Rosanna_W_voice_kr_ready3-01.wav",
  "Rosanna_W_voice_kr_ready4.wav",
  "Rosanna_W_voice_kr_ready5-01.wav",
  "Rosanna_W_voice_kr_ready6.wav",
  "Rosanna_W_voice_kr_ready7.wav",
  "Rosanna_W_voice_kr_ready8.wav",
  "Rosanna_W_voice_kr_ready9_01.wav",
  "Rosanna_W_voice_kr_recruit1-01.wav",
  "Rosanna_W_voice_kr_recruit2-01.wav",
  "Rosanna_W_voice_kr_recruit3_05.wav",
  "Rosanna_W_voice_kr_skill1-01.wav",
  "Rosanna_W_voice_kr_skill2-01.wav",
  "Rosanna_W_voice_kr_skill2_1_01.wav",
  "Rosanna_W_voice_kr_skill2_2_01.wav",
  "Rosanna_W_voice_kr_skill3-01.wav",
  "Rosanna_W_voice_kr_skill3_1_1.wav",
  "Rosanna_W_voice_kr_skill3_1_2.wav",
  "Rosanna_W_voice_kr_skill3_2_1.wav",
  "Rosanna_W_voice_kr_skill3_2_2.wav",
  "Rosanna_W_voice_kr_skill3_3_1.wav",
  "Rosanna_W_voice_kr_skill3_3_2.wav",
  "Rosanna_W_voice_kr_skill3_4_1.wav",
  "Rosanna_W_voice_kr_skill3_4_2.wav",
  "Rosanna_W_voice_kr_skill3_5_1.wav",
  "Rosanna_W_voice_kr_skill3_5_2.wav",
  "Rosanna_W_voice_kr_skill3_6_1.wav",
  "Rosanna_W_voice_kr_skill3_6_2.wav",
  "Rosanna_W_voice_kr_skill3_fire1.wav",
  "Rosanna_W_voice_kr_skill3_fire2.wav",
  "Rosanna_W_voice_kr_skill3_fire_down.wav",
  "Rosanna_W_voice_kr_skill3_ready1.wav",
  "Rosanna_W_voice_kr_skill3_ready2.wav",
  "Rosanna_W_voice_kr_skill3_ready3.wav",
  "Rosanna_W_voice_kr_skill3_ready_up.wav",
  "Rosanna_W_voice_kr_skill3_smile.wav",
  "Rosanna_W_voice_kr_skill4-02.wav",
  "Rosanna_W_voice_kr_skill5-01.wav",
  "Rosanna_W_voice_kr_skill6.wav",
  "Rosanna_W_voice_kr_skill7-02.wav",
  "Rosanna_W_voice_kr_skill8-01.wav",
  "Rosanna_W_voice_kr_speak1-01.wav",
  "Rosanna_W_voice_kr_speak10-01.wav",
  "Rosanna_W_voice_kr_speak11.wav",
  "Rosanna_W_voice_kr_speak12.wav",
  "Rosanna_W_voice_kr_speak13-01.wav",
  "Rosanna_W_voice_kr_speak14-01.wav",
  "Rosanna_W_voice_kr_speak15.wav",
  "Rosanna_W_voice_kr_speak16.wav",
  "Rosanna_W_voice_kr_speak17.wav",
  "Rosanna_W_voice_kr_speak18_01.wav",
  "Rosanna_W_voice_kr_speak19_01.wav",
  "Rosanna_W_voice_kr_speak2-01.wav",
  "Rosanna_W_voice_kr_speak20.wav",
  "Rosanna_W_voice_kr_speak21.wav",
  "Rosanna_W_voice_kr_speak22.wav",
  "Rosanna_W_voice_kr_speak23.wav",
  "Rosanna_W_voice_kr_speak24.wav",
  "Rosanna_W_voice_kr_speak25_01.wav",
  "Rosanna_W_voice_kr_speak26_01.wav",
  "Rosanna_W_voice_kr_speak27_01.wav",
  "Rosanna_W_voice_kr_speak28_01.wav",
  "Rosanna_W_voice_kr_speak29.wav",
  "Rosanna_W_voice_kr_speak3-01.wav",
  "Rosanna_W_voice_kr_speak30_01.wav",
  "Rosanna_W_voice_kr_speak31_01.wav",
  "Rosanna_W_voice_kr_speak32_01.wav",
  "Rosanna_W_voice_kr_speak4-01.wav",
  "Rosanna_W_voice_kr_speak5.wav",
  "Rosanna_W_voice_kr_speak6-01.wav",
  "Rosanna_W_voice_kr_speak7.wav",
  "Rosanna_W_voice_kr_speak8-02.wav",
  "Rosanna_W_voice_kr_speak9-01.wav",
  "Rosanna_W_voice_kr_think-02.wav",
  "Rosanna_W_voice_kr_victory1-01.wav",
  "Rosanna_W_voice_kr_victory2-01.wav",
  "Rosanna_W_voice_kr_victory3-01.wav",
  "Rosanna_W_voice_kr_victory4.wav",
  "Rosanna_W_voice_kr_victory5_02.wav",
  "Rosanna_W_voice_kr_victory6.wav",
  "Rosanna_W_voice_kr_welcome1.wav",
  "Rosanna_W_voice_kr_welcome2-02.wav",
  "Rosanna_W_voice_kr_welcome3-02.wav",
  "Rosanna_W_voice_kr_welcome4-01.wav"
];